config/routes.rb
DakiaWeb::Application.routes.draw do
  
  devise_for :retailers, :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :transactions do
    get :receive, :on => :collection
    resources :documents do 
      get :download, :on => :member
    end
  end

  devise_for :users, :skip => [:registrations], :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }                                     
      as :user do
        get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
        put 'users' => 'devise/registrations#update', :as => 'user_registration'            
      end
      
  get "home/index"
  root :to => "home#index"
  
  namespace :api do
    resources :users, :only => [:index, :show, :destroy, :edit] do
      post :update_password, :on => :collection
      get :register, :on => :collection, :defaults => { :format => 'xml' }
    end
    resources :transactions, :only => [:create, :show] do
      get :receive, :on => :collection
    end
  end
  
  namespace :retailers do
    resources :transactions, :only => [:index, :destroy, :new, :create, :show]
  end
  
  match 'receive' => 'transactions#receive'
  
  resources :home do
    get :careers, :on => :collection
    get :product, :on => :collection
    get :about_us, :on => :collection
    get :faqs, :on => :collection
    get :contact_us, :on => :collection
    post :thank_you, :on => :collection
  end
  
  match "about_us" => "home#about_us"
  match "careers" => "home#careers"
  match "product" => "home#product"
  match "faqs" => "home#faqs"
  match "contact_us" => "home#contact_us"
  match "thank_you" => "home#thank_you"
  
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :only =>[:new]

  def index
    if user_signed_in?
      redirect_to transactions_url
    end
    if retailer_signed_in?
      redirect_to retailers_transactions_url
    end
  end
  
  def contact_us
    @contact = Contact.new
    respond_to do |format|
      format.html # new.html.erb
    end
  end
  
  # POST /thank_you
  def thank_you
    @contact = Contact.new(params[:contact])
    respond_to do |format|
      if @contact.save
        format.html { redirect_to(contact_us_home_index_url, :notice => 'Thanks for contacting us.') }
      else
        format.html { render :action => "contact_us" }
      end
    end
  end
  
  
  
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/_login.html.erb
<%= form_for("user", :url => user_session_path, :class=>"form-inline") do |f| %>
  <%= f.text_field :mobile, :class => "input-small", :placeholder => "Mobile Number", :maxlength => "13"%>
  <%= f.password_field :password, :class => "input-mini", :maxlength => "6", :placeholder => "Password" %>
  <%= f.submit 'Login', :class => "btn btn-warning", :input_html => {} %>
<% end %>

app/views/home/about_us.html.erb
<h1>About us</h1>
<hr>
<h4>eDakia - ई-डाकिया </h4>
<br>
<p>Today in this digital world with Mobile, Voice Call, SMS, Internet, 3G and E-Mail, still it's really hard to send or share hard copy or Rich text documents with anyone who is not on Internet or not having an E-Mail ID. We ourself look out for a Cyber-Cafe or FAX for the aided help and end up paying whopping price even for a single page according to our market research.</p>
<br>
<h4>Problem </h4>
<br>
<p>Reality is only 7% population of India is on Internet and hence 93% don't even have an Email-ID. We can not deny the fact that E-Mail is the best application ever built and it's the primary reason we are connected to this digital world. On the other side, paper is used for everything e.g. bills, reports, forms, invoices, proofs, agreements, photos etc and this 93% of population either use Post, Courier service for passive transfer or FAX, cyber cafe for instant transfer. <br><br>Fax has it's own limitations including huge hardware cost, data loss issues and primarily need both sender and receiver on the machine at the very moment. Some applications help to send fax to email but FAX penetration is 8 times lower than Pakistan and is obsolete in Indian aspect.</p>
<br>
<h4>Vision </h4>
<br>
<p>Our vision is to provide a simple, instant and easy-to-use interface to help every individual send and receive documents irrespective of computer, Internet knowledge. We are leveraging mobile number as the identity on our <strong>DIGIT ONLY</strong> based system.</p>
<br>
<h4>Solution </h4>
<br>
<p>
  We have built a low cost hardware using off-the-shelf products which includes a Canon all-in-one printer-scanner, any Android Tablet and 3G Internet Stick. Our Software beautifully integrates with them and with just 2 clicks people can send documents by entering sender and recipients mobile number. <br>
  <br>Our system keep the documents safe forever and generates a Doc ID for each shared document. SMS acknowledges about document transfer and shares Doc ID between Sender and Receiver. They can now download it at their convenience on Mobile, Laptop, Cyber Cafe by visiting <%= link_to "http://www.edakia.in/receive", "http://www.edakia.in/receive", :target => "_blank"%> and entering just their mobile number and Doc ID.
</p>
<p>People acknowledged it as Document Saving Store like Banks are used for Money saving</p>

<p>Also, a person having mobile number can now send E-Mail to anyone in this world with this powerful system. One can write a letter/application/compaint on a piece of paper and using our system can send it directly to an email without having english and typing proficiency as every mobile user internally have an E-Mail ID and document(s) are emailed using their E-Mail ID e.g. {9811xxxxxx}@edakia.in</p>

<h3>It's about empowering Indians that now you can E-Mail to anyone in this world</h3>


<br>
<br>
<h1>Team</h1>
<hr>
<h4>Akshay Gupta (Co-Founder, CEO)</h4>
<br>
<address>
  Akshay is driven by the impact that eDakia can bring to the lives of more than a billion people of the country. He leads technical architecture, platform design and commercialization of eDakia. Akshay worked with two high-tech startups building complex software products. He completed his Engineering degree in Computer Science from Jamia Millia Islamia University, New Delhi. <br>
  Email: <a href="mailto:akshay@edakia.in">akshay@edakia.in</a><br>
</address>


<h4>Amit Sharma (Co-Founder, CTO)</h4>
<br>
<address>
  Amit is driven by an opportunity to impact the lives of more than a billion people through eDakia. He leads software development including Android app development, device drivers and eDakia's web application. Amit worked with TCS and served global Apple Inc. He completed his Engineering degree in Computer Science from Jamia Millia Islamia University, New Delhi. Amit and Akshay went to the same class at University.<br>
  Email: <a href="mailto:amit@edakia.in">amit@edakia.in</a><br>
</address>

<h4>Piyush Gupta (Advisor & Investor)</h4>
<br>
<address>
  Piyush is an entrepreneur and VP-Product at Eko. While commercializing Mobile Banking and Money Transfer solutions in remote areas, he closely witnessed low penetration of Internet connectivity and people's struggle to access basic Internet services like Email and Document sharing despite great telecom connectivity. After several discussions and observation, he conceptualized a low-cost hardware device that leverages GSM connectivity and users's Cellphone number as an identity to send and receive documents to any email address globally thus enabling universal access to email service. He developed the initial product design and commercial model for eDakia. He is now an investor and advisor to the founding team to commercialize eDakia's innovative solution. Piyush is an engineering graduate from Cochin University of Science And Technology.<br>
  Email: <a href="mailto:piyush@edakia.in">piyush@edakia.in</a><br>
</address>
<br>
<br>

app/views/home/careers.html.erb
<script type="text/javascript" id="rbox-loader-script">
_rbox = { host_protocol:document.location.protocol, ready:function(cb){this.onready=cb;} };
(function(d, e) {
    var s, t, i, src=['/static/client-src-served/widget/6950/rbox_api.js', '/static/client-src-served/widget/6950/rbox_impl.js'];
    t = d.getElementsByTagName(e); t=t[t.length - 1];
    for(i=0; i<src.length; i++) {
        s = d.createElement(e); s.src = _rbox.host_protocol + '//w.recruiterbox.com' + src[i];
        t.parentNode.insertBefore(s, t.nextSibling);
    }})(document, 'script');
</script>

app/views/home/contact_us.html.erb
<h1>Contact Us</h1>
<hr>
<div class="left">
  <p>We will be happy to help you or hear your thoughts.</p>
  <p>You can give us a call, send an E-mail or directly write to us.</p>
  <br>
  <br>
  <h4>Akshay Gupta</h4>
  <br>
  <p>New Delhi (capital region), India</p>
  <p>Mobile: +91-9711335593</p>
  <p>E-Mail ID: <%= link_to "akshay@edakia.in", "mailto:akshay@edakia.in"%>
  <br>
  <br>
  <h4>Shikha Jain</h4>
  <br>
  <p>Gurgaon, Haryana, India</p>
  <p>E-Mail ID: <%= link_to "shikha@edakia.in", "mailto:shikha@edakia.in"%>
  <br>
  <br>
  <p>Or</p>
  <br>
  <p>Just write to us here</p>
  <hr>
  <%= simple_form_for @contact, :url => thank_you_home_index_path, :html => { :class => 'form-horizontal' } do |f| %>
    
    <%= f.input :name, :label => "Your Name"%>
    
    <%= f.input :mobile, :label => "Mobile Number", :placeholder => '98xxxxxx00', :input_html => {:maxlength => 13} %>
    
    <%= f.input :email, :label => "Email-ID", :placeholder => 'name@domain.com' %>
    
    <%= f.input :company, :label => "Company" %>
    
    <%= f.input :message, :label => 'Message', :input_html => {:rows => "4"}%>
    
    <div align="center"><%= f.submit "Submit", :class => "btn btn-warning" %></div>
  <% end %>
  
  
  
</div>
<div class="span4 left hidden-phone">
  <%= image_tag("mascot.jpg", :max_width => "200")%>
</div>

<div class="clear"></div>

app/views/home/faqs.html.erb
<h1>FAQ</h1>
<hr>
<p>Ques - <strong>What is eDakia?</strong></p>
<p>Ans  - <em>eDakia is a medium to send, share, store documents (hard copy or soft copy) instantly using mobile numbers.</em></p>
<br>
<p>Ques - <strong>Is it a hardware or software?</strong></p>
<p>Ans  - <em>For hard copy: It's a combination of both hardware and software. <br>For Soft copy: It's purely a software based application.</em></p>
<br>
<p>Ques - <strong>What are the types of documents one can share?</strong></p>
<p>Ans  - <em>Hard Copy: Any documents e.g. ID proofs, reports, bills, invoices, photos, cards, forms etc. <br>Soft Copy: Images (jpg, jpeg, gif, png), documents (pdf, doc, docx, xls, ppt, txt).</em></p>
<br>
<p>Ques - <strong>How does it work?</strong></p>
<p>Ans  - <em>1. Hard copy: The hardware scans the document to digital file using Canon-all-in-one-printer-scanner (wi-fi models). This digitized copy can now be shared between people having mobile phones.<br>
  2. Soft Copy: It can directly be shared from our web application after logging at <%= link_to "http://www.edakia.in", "http://www.edakia.in" %><br><br>
  An SMS is sent to both sender's and receiver's mobile phone with a unique Doc ID of the post. <br> Now receiver and even the sender can access this document anytime, anywhere on mobile, laptop or any internet location by visiting <%= link_to "http://www.edakia.in/receive", "http://www.edakia.in/receive" %> and entering their mobile number and the Doc ID received on SMS.</em></p>

<br>  
<p>Ques - <strong>Does the recipient also need to be registered?</strong></p>
<p>Ans  - <em>No. Post can be accessed without registration and just by entering mobile number and Doc ID received in the SMS.</em></p>



<br>  
<p>Ques - <strong>Is it a Fax?</strong></p>
<p>Ans  - <em>It resembles to a FAX but has significant differentiating factors.</em>
    <table class="table table-bordered" style="width:50%">  
        <thead>
          <th>Fax</th>
          <th>eDakia</th>
        </thead>
        <tbody>
          <tr>
            <td>Fax Machine Number</td>
            <td>Mobile Number</td>
          </tr>
          <tr>
            <td>Telephone network (PSTN)</td>
            <td>Internet and Mobile network (wireless)</td>
          </tr>
          <tr>
            <td>Document never saved</td>
            <td>Store and send</td>
          </tr>
          <tr>
            <td>Multiple recipients not possible</td>
            <td>Multiple recipients possible</td>
          </tr>
          <tr>
            <td>Possible on FAX machine only</td>
            <td>Anytime anywhere</td>
          </tr>
          <tr>
            <td>Huge hardware cost</td>
            <td>Half the hardware cost <br> Multiple utility hardware</td>
          </tr>
          <tr>
            <td>E-Mail not possible</td>
            <td>E-Mail anywhere in the world</td>
          </tr>
      </tbody>
    </table>
</p>

<br>  
<p>Ques - <strong>Can I send multiple papers?</strong></p>
<p>Ans  - <em>Yes. Our software automatically creates a single pdf file of all the papers.</em></p>

<br>  
<p>Ques - <strong>Can I send E-mail?</strong></p>
<p>Ans  - <em>Yes. Once registered we create an E-Mail ID for your mobile number e.g. 981111xxxx@edakia.in and when you send an E-Mail it will be received from your mobile number based E-Mail ID.</em></p>

<br>  
<p>Ques - <strong>Receiver: When some one send a document on my mobile number, can I receive it directly in my inbox?</strong></p>
<p>Ans  - <em>Yes. In that case you need to register and update your E-Mail ID in your account details. Now next time when someone sends a post, you will receive an SMS and mail directly in your inbox.</em></p>

<br>  
<p>Ques - <strong>Can I send any document on FAX?</strong></p>
<p>Ans  - <em>Yes. We are currently working on it and soon documents can be directly transmitted to a fax number provided by you.</em></p>

<br>  
<p>Ques - <strong>How safe is it to post with eDakia?</strong></p>
<p>Ans  - <em>We use cutting edge technologies including cloud storage and computing. It's the most secure environment and we transmits all data over HTTPS. Everything is automated with no human intervention. Also, we will never share any user property or data with any person or company. It's our constant endeavor to keep users data safe in secure environment.</em></p>

<br>  
<p>Ques - <strong>What is eDakia Kendra?</strong></p>
<p>Ans  - <em>Any shopkeeper can enable eDakia services using our machine. It's way simple and easy to use as compared to computers and laptops and is virus-free.</em></p>

<br>  
<p>Ques - <strong>How about setting up a mini-cyber-café?</strong></p>
<p>Ans  - <em>Yes. This low-cost infrastructure is well suited for setting up a mini cyber café in any region. Café can easily run in power-loss situations without any need of generator backup. Also, the system is virus-free, hence it's easy to manage without any virus chaos. eDakia services on top of it can make it super easy and standardize many processes.</em></p>

<br>  
<p>Ques - <strong>How much is the machine cost if I wish to setup eDakia Kendra?</strong></p>
<p>Ans  - <em>Machine comprises of off-the-shelf products i.e. Canon all-in-one-printer-scanner (wi-fi model), Excellent Android Tablet, Internet 3G dongle, small 3G wi-fi router and a numeric keypad for number input and will currently cost around 12K INR. </em></p>


<br>  
<p>Ques - <strong>I have a printer and scanner and also own a Tablet?</strong></p>
<p>Ans  - <em>Great. But currently we support Canon wifi model only. If you already own a Android Tablet, we charge nothing for our software.</em></p>

<br>  
<p>Ques - <strong>How does eDakia make money?</strong></p>
<p>Ans  - <em>For online users: it's absolutely free of cost with a limit of 10 posts per week <br>
  For Retailer Model: It's a prepaid model and we charge very nominal fee per transaction.</em></p>

<br>  
<p>Ques - <strong>Are there any other services associated along with eDakia services?</strong></p>
<p>Ans  - <em>We are currently working on different services to make it super simple and that can enable more business for retailers e.g. Fax, Consumer complaints, Resume Building, Job Applications etc.</em></p>

<br>  
<p>Ques - <strong>I'm  a retailer and how can I enable eDakia services?</strong></p>
<p>Ans  - <em>Please <%= link_to "contact us", "/contact_us" %> and we will help you setup and enable in a day.</em></p>

app/views/home/index.html.erb
<br>
<div id="homeCarousel" class="carousel slide hidden-phone" >
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item" align="center">
      <%= image_tag("home.png") %>
    </div>
    <div class="item"  align="center">
      <%= image_tag("openhouse.png") %>
      <div class="carousel-caption">
        <h4>Open House @IITD - Prototype</h4>
        <p>Appreciation, motivation to take it further</p>
      </div>
    </div>
    <div class="item" align="center">
      <%= image_tag("launch.png") %>
      <div class="carousel-caption">
        <h4>Working at Shop - Launch</h4>
        <p>No Computer, No Email ID, No English. Send and receive Hard Copy Documents using eDakia amazed everyone</p>
      </div>
    </div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#homeCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#homeCarousel" data-slide="next">&rsaquo;</a>
</div>

<br>

<br>

<h1>Bringing email to every citizen. </h1>
<br>
<h3>Now write, send and receive mails instantly without the knowledge of computers.</h3>
<br>
<br>
  <div style="background-color:#fff;">
    <div class="right">
      <%= image_tag("mascot_medium.jpg")%>
    </div>
    <h3>ना घर का पता, ना कंप्यूटर, ना इन्टरनेट | आपका मोबाइल आपका E-Mail. </h3>
    <br>
    <div>
      <h2> अब मोबाइल नंबर से मोबाइल नंबर पे तुरंत डाक भेजे |</h2>
      <br>
      
      <br>
      <h2>Simple . Instant .  Language Independent</h2>
    </div>
    <div class="clear"></div>  
  </div>
  <br>
  <br>
  <p><small>All your documents will be safe in our <strong>SECURE CLOUD FOREVER.</strong></small></p>
  <p class="lead">FREE Registration. Call <strong>011-30715555</strong> and Press 1 from your Mobile </p>
<br>
<br>
<div class="well right">
  <blockquote><p>It's the Indian answer to Email</p> <small><em>Shardul Mohite, Webonise Lab</em></small></blockquote>
  <blockquote><p>It will empower everyone to send and receive email</p></blockquote>
  <blockquote><p>Only numbers based system is convincing </p></blockquote>
</div>

app/views/home/new.html.erb
<h4><%= "Welcome #{@user.mobile}" %></h4>

app/views/home/product.html.erb
<h1>Product</h1>
<hr>
<p>eDakia product is much more than a application that run on top of any Android based mobile or tablet. It beautifully integrates with wireless Canon all-in-one-printer-scanner models. <em>It empowers any individual to send and receive posts just based on Mobile Numbers.</em></p>
<br>
<p><strong> ➠</strong> The whole system is <strong>Number based</strong> which makes it super easy to use by any literate or non-literate person.</p>
<br>
<p><strong> ➠</strong> Anyone can directly E-Mail their letters, application, forms, requests, documents <strong>without english typing, computer proficiency and file attachment hassles.</strong></p>
<br>
<p><strong> ➠</strong> Besides sending and receiving posts, eDakia acts like a <strong>Document Store</strong> for saving a copy of important documents like ID proofs, pan card, reports, agreements etc with an ease to access them anytime in case of urgency.</p>
<br>
<p><strong> ➠</strong> Internally, it also creates a mobile number based E-Mail ID for registered users e.g. 981111xxxx@edakia.in. It helps user to receive <strong>email along with an SMS notification</strong> from anyone in the world.</p>
<br>
<br>


<h2>Reach</h2>
<hr>
<p><strong> ➠</strong> We are enabling <strong>eDakia kendra or mini-cyber-café</strong> at the hyper-local level to provide eDakia services in your vicinity.</p>
<br>
<p><strong> ➠</strong> We are also integrating with existing cyber-café to provide eDakia services at nominal cost.</p>
<br>
<p><strong> ➠</strong> We have absolute plans to go Pan-India level for maximum benefits and empowerment of every citizen.</p>
<br>
<p><strong> ➠</strong> We also plan to partner with enterprises, organizations, schools to help them communicate with their employees, vendors, parents etc.</p>
<br>
<br>

<h2>How it works?</h2>
<hr>
<h3>Send</h3>
<br>
<p><strong>Internet users: </strong> One can absolutely send files to non-internet users with the ease of sitting on your system.</p>
<p>Kindly follow the simple steps:</p>
<p><strong> ➠</strong> Registration: Call <strong>011-30715555</strong> from your mobile phone and press 1 when prompted.</p>
<p><strong> ➠</strong> Login at http://www.edakia.in with password provided to you by an SMS after successful registration.</p>
<p><strong> ➠</strong> Click Send Post, enter recipient's mobile number and attach your file and click send.</p>
<p><strong> ➠</strong> You and Recipient will receive an SMS with Doc ID.
<br>
<br>
<p><strong>Non-Internet Users: </strong></p>
<p><strong> ➠</strong> Visit eDakia kendra with your hard copy documents.</p>
<p><strong> ➠</strong> Tell your and recipient's mobile number and keep the papers in the scanner.</p>
<p><strong> ➠</strong> With 2 clicks a copy of your document(s) is securely saved and shared by an SMS acknowledgement.</p> 
<br>
<br>

<h3>Receive</h3>
<br>
<p><strong> ➠</strong> One can access absolutely from mobile (with Internet), Laptop, Desktop, eDakia Kendra, Cyber Café</p>
<p><strong> ➠</strong> Open <%= link_to "http://www.edakia.in/receive", "http://www.edakia.in/receive" %></p>
<p><strong> ➠</strong> Enter your mobile number and Doc ID received over SMS</p>
<p><strong> ➠</strong> View, download or print the documents </p>
<br>
<br>

<h3>Account</h3>
<br>
<p>Any registered user can view all the documents saved, send or received with their Doc ID by just logging in to <%= link_to "http://www.edakia.in/users/login", "http://www.edakia.in/users/login" %> 