config/routes.rb
DakiaWeb::Application.routes.draw do
  
  devise_for :retailers, :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :transactions do
    get :receive, :on => :collection
    resources :documents do 
      get :download, :on => :member
    end
  end

  devise_for :users, :skip => [:registrations], :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }                                     
      as :user do
        get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
        put 'users' => 'devise/registrations#update', :as => 'user_registration'            
      end
      
  get "home/index"
  root :to => "home#index"
  
  namespace :api do
    resources :users, :only => [:index, :show, :destroy, :edit] do
      post :update_password, :on => :collection
      get :register, :on => :collection, :defaults => { :format => 'xml' }
    end
    resources :transactions, :only => [:create, :show] do
      get :receive, :on => :collection
    end
  end
  
  namespace :retailers do
    resources :transactions, :only => [:index, :destroy, :new, :create, :show]
  end
  
  match 'receive' => 'transactions#receive'
  
  resources :home do
    get :careers, :on => :collection
    get :product, :on => :collection
    get :about_us, :on => :collection
    get :faqs, :on => :collection
    get :contact_us, :on => :collection
    post :thank_you, :on => :collection
  end
  
  match "about_us" => "home#about_us"
  match "careers" => "home#careers"
  match "product" => "home#product"
  match "faqs" => "home#faqs"
  match "contact_us" => "home#contact_us"
  match "thank_you" => "home#thank_you"
  
  

end

app/controllers/api/transactions_controller.rb
class Api::TransactionsController < ApplicationController
  before_filter :parse_serial_number
  protect_from_forgery :except => [:create, :receive]
  respond_to :xml
  
  
  # POST api/transactions.xml
  def create
    @transaction = Transaction.new(params[:transaction])
    @transaction.retailer_id = @retailer.id
    @transaction.serial_number = @machine.serial_number
    respond_to do |format|
      if @transaction.save
        @documents = @transaction.documents
        #format.html { redirect_to(@transaction, :notice => 'Mail was successfully sent.') }
        format.xml  
        #format.json  { render :json => @transaction, :status => :created, :location => @transaction }
      else
        @transaction.documents.build
        #format.html { render :action => "new"}
        format.xml  
        #format.json  { render :json => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
  # Receive /transactions/receive
  def receive
    unless params[:transaction].blank? 
      mobile = params[:transaction][:receiver_mobile]
      email = params[:transaction][:receiver_email]
      secret = params[:transaction][:document_secret]
      @transaction = Transaction.new(params[:transaction])
      if secret.blank?
        @transaction.errors.add(:base, "Doc ID is required") if secret.blank?
      elsif secret.match(/^\d{6}/).blank?
        @transaction.errors.add(:document_secret, "Must be 6 Digit Long") 
      end
      
      if email.blank? && mobile.blank?
        @transaction.errors.add(:base, "Provide Either Mobile number or Email")
      elsif !mobile.blank? && mobile.match(/(^[789]\d{9}$)/).blank?
        @transaction.errors.add(:receiver_mobile, "Invalid Number")
      elsif !email.blank? && email.match(/\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/).blank?
        @transaction.errors.add(:receiver_email, "Invalid Address")
      elsif (!email.blank? && !mobile.blank?)
        @transaction.errors.add(:base, "Enter only Mobile number or Email")
      end
      
      if @transaction.errors.blank?
        @transaction = Transaction.get_document(mobile, email, secret) 
        unless @transaction.blank?
          @documents = @transaction.documents
          user = mobile.blank? ? email : mobile
          @event = @transaction.receive_event(user, @machine.serial_number)
          #@user = User.where("mobile = ? or email = ?", user, user).select("id, mobile, balance").first
        else
          @transaction = Transaction.new(params[:transaction])
          @transaction.errors.add(:base, "Your Document not found")
        end
      end
    else
      @transaction = Transaction.new
    end
    
    if !@transaction.errors.blank? or @transaction.new_record?
      respond_to do |format|
        format.html { render :action =>  "receive", :alert => "Mail Not found"}
        format.xml {render :xml => @transaction.errors} #, :status => :unprocessable_entity}
      end
    else
      respond_to do |format|
        format.html { render :action => "receive", :locals => {:documents => @documents} }
        format.xml #receive.xml 
      end
    end
  end
  
  protected
  
  def parse_serial_number
    error = {}
    if params[:serial_number].blank? || params[:serial_number].length <= 9
      error = {:errors => { :error => "Serial Number is wrong or not provided" }}
    else
      @machine = Machine.find_by_serial_number("#{params[:serial_number]}")
      if @machine.blank?
        error = {:errors => { :error => "This eDakia machine is not registered" }} 
      elsif @machine.retailer.blank?
        error = {:errors => { :error => "This eDakia machine is not installed at any eDakia Kendra" }}
      elsif @machine.retailer.balance < Price::Retailer::MIN_BALANCE
        error = {:errors => { :error => "You have insufficient funds to carry out a transaction" }} 
      else
        @retailer = @machine.retailer
      end
    end
    unless error.blank?
      respond_to do |format|
        format.xml {render :xml => error} #, :status => :unprocessable_entity}
      end
    end
  end #parse_serial_number
  
  
  
  
end

app/controllers/retailers/transactions_controller.rb
class Retailers::TransactionsController < ApplicationController
  before_filter :authenticate_retailer!
  
  # GET retailer/transactions
  # GET /transactions.xml
  def index
    @transactions = current_retailer.transactions.order("created_at DESC")
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions }
    end
  end
  
  # GET retailers/transactions/1
  # GET retailers/transactions/1.xml
  def show
    @transaction = current_retailer.transactions.find(params[:id])
    unless @transaction.blank?
      respond_to do |format|
        format.html # show.html.erb
        format.xml
      end
    end
  end
  
  # DELETE retailers/transactions/1
  # DELETE retailers/transactions/1.xml
  def destroy
    @transaction = current_retailer.transactions.find(params[:id])
    @transaction.update(:active => false)
    @transaction.save!

    respond_to do |format|
      format.html { redirect_to(retailers_transactions_url) }
      format.xml  { head :ok }
    end
  end
  
  
  # GET retailers/transactions/new
  # GET retailers/transactions/new.xml
  def new
    @retailer_transaction = current_retailer.transactions.new
    2.times do
      @retailer_transaction.documents.build
    end
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @transaction }
    end
  end
  
  # POST retailers/transactions
   # POST retailers/transactions.xml
   def create
     @retailer_transaction = current_retailer.transactions.new(params[:transaction])
     @retailer_transaction.retailer_id = current_retailer.id
     respond_to do |format|
       if current_retailer.credit <= 0
         @retailer_transaction.errors.add(:base, "You have no credit. Please contact and buy more credit.")
         format.html { redirect_to(new_retailers_transaction_url, :alert => @retailer_transaction.errors.full_messages.join(". "))}
         format.xml {render :xml => @retailer_transaction.errors}
       elsif @retailer_transaction.save
         #@event = @retailer_transaction.send_event(params[:serial_number])
         #@document = @retailer_transaction.documents.first
         format.html { redirect_to(retailers_transactions_url, :notice => 'Mail was successfully sent.') }
         format.xml  
       else
         puts @retailer_transaction.errors.inspect
         @retailer_transaction.documents.build
         format.html { render :action => "new"}
         format.xml  
       end
     end
   end
   
   # retailer transactions log
   def retailer_txn
     @txns = current_retailer.events.order("created_at DESC")
     respond_to do |format|
       format.html # receive.html.erb
       format.xml  { render :xml => @transactions }
     end
   end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :authenticate_user!, :except => ["receive"]
  
  # GET /transactions
  # GET /transactions.xml
  def index
    @transactions = Transaction.where("sender_mobile = ? or receiver_mobile = ? or receiver_email = ?", current_user.mobile, current_user.mobile, current_user.email).includes(:documents).order("created_at DESC")
    #print request.env.inspect
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions }
      format.json  { render :json => @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.xml
  def show
    @transaction = Transaction.where("id = ? and (sender_mobile = ? or receiver_mobile = ? or receiver_email = ?)  ", params[:id], current_user.mobile, current_user.mobile, current_user.email).first
    unless @transaction.blank?
      respond_to do |format|
        format.html # show.html.erb
        format.xml
        #format.json  { render :json => @transaction }
      end
    end
  end
  
  # POST /transactions
  # POST /transactions.xml
  def create
    @transaction = Transaction.new(params[:transaction])
    respond_to do |format|
      if current_user.credit <= 0
         @transaction.errors.add(:base, "You have no credit. Please contact and buy more credit.")
         format.html { redirect_to(new_transaction_url, :alert => @transaction.errors.full_messages.join(". "))}
         format.xml {render :xml => @transaction.errors}
      elsif @transaction.save
        @document = @transaction.documents.first
        #@event = @transaction.events.first
        format.html { redirect_to(@transaction, :notice => 'Mail was successfully sent.') }
        format.xml  
        #format.json  { render :json => @transaction, :status => :created, :location => @transaction }
      else
        @transaction.documents.build
        format.html { render :action => "new"}
        format.xml  
        #format.json  { render :json => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /transactions/new
  # GET /transactions/new.xml
  def new
    @transaction = Transaction.new
    1.times do 
      @transaction.documents.build
    end
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @transaction }
    end
  end
=begin
  # GET /transactions/1/edit
  def edit
    #@transaction = Transaction.find(params[:id])
    @transaction = Transaction.where("id = ? and (sender_mobile = ? or receiver_mobile = ?)  ", params[:id], current_user.mobile, current_user.mobile)
  end

  # PUT /transactions/1
  # PUT /transactions/1.xml
  def update
    #@transaction = Transaction.find(params[:id])
    @transaction = Transaction.where("id = ? and (sender_mobile = ? or receiver_mobile = ?)  ", params[:id], current_user.mobile, current_user.mobile)

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end
=end
  # DELETE /transactions/1
  # DELETE /transactions/1.xml
  def destroy
    #@transaction = Transaction.find(params[:id])
    @transaction = Transaction.where("id = ? and (sender_mobile = ? or receiver_mobile = ?)  ", params[:id], current_user.mobile, current_user.mobile).first
    Transaction.update(@transaction.id, :active => false)

    respond_to do |format|
      format.html { redirect_to(transactions_url) }
      format.xml  { head :ok }
    end
  end
  
  
  # Receive /transactions/receive
  def receive
    unless params[:transaction].blank? 
      mobile = params[:transaction][:receiver_mobile]
      email = params[:transaction][:receiver_email]
      secret = params[:transaction][:document_secret]
      @transaction = Transaction.new(params[:transaction])
      if secret.blank?
        @transaction.errors.add(:base, "Doc ID is required") if secret.blank?
      elsif secret.match(/^\d{6}/).blank?
        @transaction.errors.add(:document_secret, "Must be 6 Digit Long") 
      end
      
      if email.blank? && mobile.blank?
        @transaction.errors.add(:base, "Provide Either Mobile number or Email")
      elsif !mobile.blank? && mobile.match(/(^[789]\d{9}$)/).blank?
        @transaction.errors.add(:receiver_mobile, "Invalid Number")
      elsif !email.blank? && email.match(/\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/).blank?
        @transaction.errors.add(:receiver_email, "Invalid Address")
      elsif (!email.blank? && !mobile.blank?)
        @transaction.errors.add(:base, "Enter only Mobile number or Email")
      end
      
      if @transaction.errors.blank?
        @transaction = Transaction.get_document(mobile, email, secret) 
        unless @transaction.blank?
          @documents = @transaction.documents
          user = mobile.blank? ? email : mobile
          @event = @transaction.receive_event(user, params[:serial_number])
          @user = User.where("mobile = ? or email = ?", user, user).select("id, mobile, balance").first
        else
          @transaction = Transaction.new(params[:transaction])
          @transaction.errors.add(:base, "Your Document not found")
        end
      end
    else
      @transaction = Transaction.new
    end
    
    if !@transaction.errors.blank? or @transaction.new_record?
      respond_to do |format|
        format.html { render :action =>  "receive", :alert => "Mail Not found"}
        format.xml {render :xml => @transaction.errors} #, :status => :unprocessable_entity}
      end
    else
      respond_to do |format|
        format.html { render :action => "receive", :locals => {:documents => @documents} }
        format.xml #receive.xml 
      end
    end
  end
end

app/helpers/api/transactions_helper.rb
module Api::TransactionsHelper
end

app/helpers/retailers/transactions_helper.rb
module Retailers::TransactionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper  
=begin
	def add_document(form_builder)
  	link_to_function "add", :id  => "add_document" do |page|
    	form_builder.fields_for :document, Document.new, :child_index => 'NEW_RECORD' do |document_form|
    	  html = render(:partial => 'document', :locals => { :f => document_form })
    	  #page << "$('add_document').insert({ before: '#{escape_javascript(html)}'.replace(/NEW_RECORD/g, new Date().getTime()) });"
    	  page << "$('#{escape_javascript(html)}'.replace(/NEW_RECORD/g, new Date().getTime())).insertBefore($('#add_document')); $('#add_document').remove();"
   		 end
  	end
	end
	
	def delete_document(form_builder)
    if form_builder.object.new_record?
      link_to_function("Remove this Document", "$(this).parent().remove()")
    else
      form_builder.hidden_field(:_delete) +
      link_to_function("Remove this Document", "this.up('fieldset').hide(); $(this).previous().value = '1'")
    end
  end
=end
end

app/views/transactions/_document.html.erb
<fieldset>
    <% if !f.object.new_record? %>
        <%= image_tag f.object.doc.url %>
    <% end %>
    
    <%= f.file_field :doc %>
    <%= delete_document(f) %>
</fieldset>

app/views/transactions/_form.html.erb
<%= simple_form_for @transaction, :html => { :multipart => true, :class => 'form-horizontal', :style=> "width: 50%;" } do |f| %>
    
    <% unless @transaction.errors.blank? %>
    <div class="alert alert-error">
      <% @transaction.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </div>
    <% end %>
    
    
    <div id="receiver_mobile">
      <%= f.input :receiver_mobile, :label => 'Receiver Mobile', :placeholder => '98xxxxxx00'%>
    </div>
    <div align="center">Or</div>
    <br>
    <div id="receiver_emails">
      <%= f.input :receiver_emails, :label => 'Receiver Email(comma separated)', :id => "receiver_emails", :placeholder => 'user@domain.com', :input_html => {:rows => "3"}%>
    </div>
    <%= f.input :sender_mobile, :as => :hidden, :input_html => { :value => current_user.mobile } %>
    <br>
    <%= f.simple_fields_for :documents, @transaction.documents.first do |document_form| %>
      <%= document_form.error :doc_content_type, :class => "alert alert-error" %>
      <%= document_form.error :doc_file_size, :class => "alert alert-error" %>
      <%= document_form.input :doc, :label => "Your File", :as => :file %>
    <% end%>
    <br>
    <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
    <%= link_to "Cancel", transactions_path, :class => "btn" %>
    <%= f.button :submit, "Send Mail", :class => "btn-large btn-warning" %>
  
<% end %>

app/views/transactions/_form_send.html.erb
<%= form_for(@transaction, :html => {:multipart => true}) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p><%= f.label :receiver_mobile %> <br>
  <%= f.text_field :receiver_mobile %> <br>
  Or <br>
  <%= f.label :receiver_email %> <br>
  <%= f.email_field :receiver_email %> </p>

  <%= f.hidden_field :sender_mobile, :value => current_user.mobile %>
 
  <%#= add_document(f) %>
  
  <%= f.fields_for :document, @transaction.document do |document_form| %>
      <p><%= document_form.label :doc, "Doc File" %>
      <%= document_form.file_field :doc %>
      <%= document_form.hidden_field :user_id, :value => current_user.id %>
      </p>
  <% end %>
  
  <div class="actions">
    <%= f.submit "Send Mail", :class => "button green" %>
  </div>
<% end %>




<%= form_for @transaction, :html => { :class => 'form-vertical' } do |f| %>
  <div class="control-group">
    <%= f.label :receiver_mobile, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :receiver_mobile, :class => 'text_field' %>
    </div>
  </div>
  <div class="controls">
    Or
  </div>
  <br>
  <div class="control-group">
    <%= f.label :receiver_email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :receiver_email, :class => 'text_field' %>
    </div>
  </div>
  <%= f.hidden_field :sender_mobile, :value => current_user.mobile %>
  
  <%= f.fields_for :document, @transaction.document do |document_form| %>
    <div class="control-group">
      <%= document_form.label :doc, :class => 'control-label' %>
      <div class="controls">
        <%= document_form.file_field :doc, :class => 'file_field' %>
      </div>
    </div>
      <p><%#= document_form.label :doc, "Doc File" %>
      <%#= document_form.file_field :doc %>
      <%= document_form.hidden_field :user_id, :value => current_user.id %>
      </p>
  <% end %>

  <div class="form-actions">
    <%= f.submit "Send Mail", :class => 'btn btn-primary' %>

  </div>
<% end %>

app/views/transactions/edit.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/transactions/index.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h1><%#=t '.title', :default => model_class.model_name.human.pluralize %>All Mails<%= " (#{number_to_phone(current_user.mobile)})"%></h1>
</div>

<%#= link_to t('.new', :default => t("helpers.links.new")),
            new_transaction_path,
            :class => 'btn btn-primary' %>

<%= link_to "New Post",
new_transaction_path,
:class => 'btn btn-warning' %>
            
<table class="table table-striped">  
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= "Document" %></th>
      <th><%= model_class.human_attribute_name(:document_secret) %></th>
      <th><%= model_class.human_attribute_name(:sender_mobile) %></th>
      <th><%= model_class.human_attribute_name(:receiver_mobile) %></th>
      <!--<th><%#= model_class.human_attribute_name(:receiver_email) %></th> -->
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each_with_index do |transaction, i| %>
      <% unread = (current_user.id == transaction.receiver_id && transaction.unread?) ? "class='unread'" : ""%>
      <tr <%= unread %> >
        <td><%= link_to i+1, transaction_path(transaction) %></td>
        <td>
          <% transaction.documents.each do |doc| %>
            <%= link_to doc.doc_file_name, download_transaction_document_path(:transaction_id => transaction.id, :id => doc.id), :target => "_blank", :class => " btn btn-mini" %>
           <br>
          <% end %>
        
        <td><%= transaction.document_secret %></td>
        <td><%= transaction.sender_mobile %></td>
        <td><%= transaction.receiver_mobile %><br><%= transaction.receiver_email %></td>
        <!-- <td><%#= transaction.receiver_email %></td> -->
        <td><%#=l transaction.created_at %>
          <% if transaction.created_at.to_date == Date.today  %>
            <%= transaction.created_at.strftime("%I:%M %p")     %>
          <% else %>
            <%= transaction.created_at.strftime("%d-%b-%Y %I:%M") %>
          <% end   %>
        </td>
        <td>
          <%#= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_transaction_path(transaction), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      transaction_path(transaction),
                      :method => :delete,
                      :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/transactions/new.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New Post") %>
      <%#= :default => "New #{model_class.model_name.human}") %>
  </h1>
</div>
<%= render :partial => 'form' %>

app/views/transactions/receive.html.erb
<h1>Receive Mail</h1>
<hr>
<% if current_user.blank? and current_retailer.blank? %>
  <div class="span4 left hidden-phone">
    <%= image_tag("mascot.jpg", :max_width => "200")%>
  </div>
<% end%>


<% if @transaction.new_record? %>

  <%= simple_form_for @transaction, :url => receive_transactions_url,  :html => {:method => :get, :class => "form-vertical left"} do |f| %>
      <% unless @transaction.errors.blank? %>
        <p class="alert alert-error">
          <% @transaction.errors.full_messages.each do |msg| %>
            <%= msg %><br>
          <% end %>
        </p>
      <% end%>
    
      <div id="receiver_mobile" class="left">
        <%= f.input :receiver_mobile, :label => 'Receiver Mobile', :placeholder => '98xxxxxx00', :input_html => {:maxlength => 10}%>
      </div>
      <div id="receiver_email" style="display:none" class="left">
        <%= f.input :receiver_email, :label => 'Receiver Email', :id => "receiver_email", :placeholder => 'user@domain.com'%>
      </div>
    
      <div class="left" style="margin: 22px 0 0 20px;">
        <button id="mobile_toggle" type="button" class="btn btn-warning" data-complete-text="Email" data-toggle="button">Email</button>
      </div>
    
      <div class="clear"></div>
      <div id="document_secret">
        <%= f.label :document_secret, "Doc ID" %>
        <%= f.password_field :document_secret, :input_html => {:maxlength => 6} %>
      
        <%#= f.input :document_secret, :label => 'Doc ID', :hint => false, :input_html => {:maxlength => 6} %>
      </div>
      <br>
      <br>
      <%= f.button :submit, "Receive Mail", :class => "btn-large btn-warning" %>
  
  <% end %>
<% elsif documents %>
    <% documents.each do |doc| %>
     <h3><%= doc.doc_file_name %>&nbsp;&nbsp;&nbsp;<%= link_to "View", URI.encode(doc.doc.url), :target => "_blank", :class => " btn btn-small" %></h3>
     <br>
    <% end %>
<% end %>

app/views/transactions/retailer_txn.html.erb
<h1>Total Transactions: <%= @txns.size %></h1>

<br>
<%- model_class = Event -%>
            
<table class="table table-striped">  
  <thead>
    <tr>
      <th>S.No.</th>
      <th><%= model_class.human_attribute_name(:user) %></th>
      <th><%= model_class.human_attribute_name(:action) %></th>
      <th><%= model_class.human_attribute_name(:cost) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @txns.each_with_index do |txn, i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%= txn.user %></td>
        <td><%= txn.action %></td>
        <td><%= txn.cost %></td>
        <td><%#=l transaction.created_at %>
          <% if txn.created_at.to_date == Date.today  %>
            <%= txn.created_at.strftime("%I:%M %p")     %>
          <% else %>
            <%= txn.created_at.strftime("%d-%b-%Y %I:%M") %>
          <% end   %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/transactions/show.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h1>Mail Details</h1>
</div>

<table class="table table-bordered" style="width:50%">  
  <tbody>
      <tr>
        <td>Mail ID</td>
        <td><%= @transaction.id %>
      <tr>
        <td>Sender Mobile</td>
        <td><%= @transaction.sender_mobile %></td>
      </tr>
      <tr>
        <td>Receiver Mobile</td>
        <td><%= @transaction.receiver_mobile %></td>
      </tr>
      <tr>
        <td>Receiver E-Mails</td>
        <td>
        <%= @transaction.receiver_email %><br>
        <% unless @transaction.receiver_emails.blank? %>
          <% @transaction.receiver_emails.split(",").each do |email| %>
            <%= email %>
            <br>
          <% end %>
        <% end %>
        </td>
      </tr>
      <tr>
        <td>Number of Files</td>
        <td><%= @transaction.documents.count %></td>
      </tr>
      <tr>
        <td>File Names</td>
        <td><% @transaction.documents.each do |doc| %>
          <%= link_to doc.doc_file_name, download_transaction_document_path(:transaction_id => @transaction.id, :id => doc.id), :target => "_blank" %>
         <br>
        <% end %>
        </td>
      </tr>
      <tr>
        <td>Sending Time</td>
        <td>
          <% if @transaction.created_at.to_date == Date.today  %>
            <%= @transaction.created_at.strftime("%I:%M %p")     %>
          <% else %>
            <%= @transaction.created_at.strftime("%d-%b-%Y %I:%M") %>
          <% end   %>
        </td>
      </tr>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              transactions_path, :class => 'btn'  %>
  <%#= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_transaction_path(@transaction), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              transaction_path(@transaction),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
              
</div>