config/routes.rb
DakiaWeb::Application.routes.draw do
  
  devise_for :retailers, :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :transactions do
    get :receive, :on => :collection
    resources :documents do 
      get :download, :on => :member
    end
  end

  devise_for :users, :skip => [:registrations], :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }                                     
      as :user do
        get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
        put 'users' => 'devise/registrations#update', :as => 'user_registration'            
      end
      
  get "home/index"
  root :to => "home#index"
  
  namespace :api do
    resources :users, :only => [:index, :show, :destroy, :edit] do
      post :update_password, :on => :collection
      get :register, :on => :collection, :defaults => { :format => 'xml' }
    end
    resources :transactions, :only => [:create, :show] do
      get :receive, :on => :collection
    end
  end
  
  namespace :retailers do
    resources :transactions, :only => [:index, :destroy, :new, :create, :show]
  end
  
  match 'receive' => 'transactions#receive'
  
  resources :home do
    get :careers, :on => :collection
    get :product, :on => :collection
    get :about_us, :on => :collection
    get :faqs, :on => :collection
    get :contact_us, :on => :collection
    post :thank_you, :on => :collection
  end
  
  match "about_us" => "home#about_us"
  match "careers" => "home#careers"
  match "product" => "home#product"
  match "faqs" => "home#faqs"
  match "contact_us" => "home#contact_us"
  match "thank_you" => "home#thank_you"
  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>eDakia</title>
  <link rel="shortcut icon" href="/assets/favicon.ico" />
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div class="header" style="width: 900px; margin: auto;">
	<% if user_signed_in? %>  
		<%= link_to image_tag("logo.jpg"), "/transactions" %> 
	<% else %>  
		<%= link_to image_tag("logo.jpg"), "/" %> 
    <% end %>
	<div class="right">
	  <% if user_signed_in? %>  
		<%= link_to current_user.mobile, edit_user_registration_path %> | <span><%= link_to "Sign out", destroy_user_session_path, :class => "button gray small" %></span>
		<span><%= link_to "Get Mail", receive_transactions_url, :class => "button gray small" %></span> 
		<span><%= link_to "Send Mail", new_transaction_url, :class => "button gray small" %></span>
	  <% else %>
		<span><%= link_to "Login", new_user_session_url, :class => "button gray small" %></span>  
		<span><%= link_to "Register", new_user_registration_url, :class => "button gray small" %></span> 
		<span><%= link_to "Get Mail", receive_transactions_url, :class => "button gray small" %></span> 
		<span><%= link_to "Send Mail", new_transaction_url, :class => "button gray small" %></span>
	  <% end %>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
	</div>

  </div>
  <div class="content-wrapper">
	<div class="content">
		<%= yield %>
	</div>
  </div>
</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "eDakia" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'http://25.media.tumblr.com/avatar_f041527b49a3_16.png', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-collapse">
                              <span class="icon-bar"></span>
                              <span class="icon-bar"></span>
                              <span class="icon-bar"></span>
                            </a>
          <% if user_signed_in? %>  
        		<%= link_to image_tag("logo.png", :width => "180"), "/transactions", :class => "brand" %> 
          <% elsif retailer_signed_in? %>  
            <%= link_to image_tag("logo.png", :width => "180"), retailers_transactions_url, :class => "brand" %> 
        	<% else %>  
        		<%= link_to image_tag("logo.png", :width => "180"), "/", :class => "brand" %> 
          <% end %>
          <div class="nav-collapse collapse navbar-collapse">
            <ul class="nav" >
              <li><%= link_to "About us", "/about_us" %></li>
              <li><%= link_to "Product", "/product" %></li>
              <li><%= link_to "Blog", "http://blog.edakia.in", :target => "_blank" %></li>
              <li><%= link_to "FAQ", "/faqs" %></li>
              <li><%= link_to "Careers", "/careers#op-12785-gogetters-hustlers" %></li>
              <li><%= link_to "Contact Us", "/contact_us" %></li>
            </ul>
            <ul class="nav pull-right" >
              <% if user_signed_in? %> 
                <li><%= link_to current_user.mobile + " (#{current_user.unread_count})", edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path  %></li>
              <% elsif retailer_signed_in? %> 
                <li><%= link_to current_retailer.mobile, edit_retailer_registration_path %></li>
                <li><%= link_to "Logout", destroy_retailer_session_path  %></li>
              <% else %>
                <li><%#= link_to "Login", new_user_session_url  %></li>
                <li><%= render :partial => "home/login"%></li>
                <li><%= link_to "Receive Mail", "/receive"  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
      <div style="background: url(/assets/postage.png) repeat-x; height: 6px;"></div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <% if user_signed_in? %>
        <div class="span2">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li>Credit: <%= current_user.credit  %></li>
                <%#= render :partial => "home/login"%>
              <li><%= link_to "Send Post", new_transaction_url  %></li>
              <li><%= link_to "All Posts (#{current_user.unread_count})", transactions_url  %></li>
              <li><%= link_to "Update Profile", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path  %></li>           
            </ul>
          </div><!--/.well -->
          <%= image_tag("mascot.jpg", :max_width => "286")%>
        </div><!--/span-->
        <div class="span10 content">
        <% elsif retailer_signed_in? %>
          <div class="span2">
            <div class="well sidebar-nav">
              <ul class="nav nav-list">
                <li>Credit: <%= current_retailer.credit  %></li>
                <li><%= link_to "Send Mail", new_retailers_transaction_url  %></li>
                <li><%= link_to "Receive Mail", "/receive"  %></li>
                <li><%= link_to "Mail Tracking", retailers_transactions_url  %></li>
                <li><%= link_to "Update Profile", edit_retailer_registration_path %></li>
                <li><%= link_to "Logout",  destroy_retailer_session_path %></li>
              </ul>
            </div><!--/.well -->
            <%= image_tag("mascot.jpg", :max_width => "286")%>
          </div><!--/span-->
          <div class="span10 content">
        <% else %>
          <div class="span2"></div>
          <div class="span8 content">
        <% end%>
            <% unless notice.blank? %>
              <div class="alert alert-success"><%= notice %></div>
            <% end %>
            <% unless alert.blank? %>
        		  <div class="alert alert-error"><%= alert %></div>
        		<% end %>
            <%= yield %>
          </div>
        </div>
        <div class="active hidden-phone" id="feedback_bt">
            <a href="mailto:email%40edakia%2Ein"></a>
        </div>
      </div><!--/row-->
     <br>
     <br>
      <footer>
        <div class="row-fluid">
          <div class="span1">
          </div>
          <div class="span6">
            <div class="row-fluid">
              <div class="span1"><%= link_to "About", "/about_us" %></div>
              <div class="span1"><%= link_to "Blog", "http://blog.edakia.in", :target => "_blank" %></div>
              <div class="span1"><%= link_to "FAQ", "/faqs"  %></div>
              <div class="span1"><%= link_to "Jobs", "/careers#op-12785-gogetters-hustlers" %></div>
              <div class="span2"><%= link_to "Contact Us", "/contact_us" %></div>
              <div class="span1"><%= link_to "Retailer", "/retailers/login" %></div>
            </div>
          </div>
          <div class="span4">
            <em>Copyright &copy; 2012 eDakia India, All rights reserved.</em>
            <br>
            <br>
            <table cellpadding="0" cellspacing="0" border="0">
              <tbody>
                <tr>
                  <td ><fblike><img src="https://img.createsend1.com/img/templatebuilder/like-glyph.png" border="0" width="8" height="14" alt="Facebook icon"></fblike></td>
                  <td width="3"></td>
                  <td ><div class="header-content"><!-- <fblike>Like</fblike> --><a href="https://www.facebook.com/edakia" target="_blank">Like</a></div></td>
                  <td width="10"></td>
                  <td ><tweet><img src="https://img.createsend1.com/img/templatebuilder/tweet-glyph.png" border="0" width="17" height="13" alt="Twitter icon"></tweet></td>
                  <td width="3"></td>
                  <td ><div class="header-content"><!-- <tweet>Tweet</tweet> --><a href="https://twitter.com/eDakia" target="_blank">Tweet</a></div></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </footer>
    </div> <!-- /container -->
    
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <%= javascript_include_tag "application" %>
    
    <!-- Google analytics code -->
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-36993487-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
  </body>
</html>